use ThinkQPortable;
create table movie (movieid int,moviename varchar(25));
alter table movie add rating int;
alter table movie alter column moviename varchar(40);
alter table movie  add  moviename varchar(23);
alter table movie drop column moviename;
alter table movie alter column movieid int not null;
alter table movie add primary key(movieid);
alter table movie drop constraint PK__movie__42EACB664128825D;
select*from movie;
sp_help movie;